const productsList = [{
    id:1,
    name:"Asus ROG Zephyrus G14",
    color:"Silver",
    price:"$1425",
    rating:3.8,
    votes:1,
    category:"laptops",
},
{
    id:2,
    name:"Lenovo Thinkpad E470",
    color:"Red",
    price:"$725",
    rating:4.1,
    votes:2,
    category:"laptops",
},
{
    id:3,
    name:"Sennheiser RS 110 II On-Ear Wireless",
    color:"Black",
    price:"$24",
    rating:4.1,
    votes:12,
    category:"speakers",
},
{
    id:4,
    name:"Macbook Pro 16inch",
    color:"Silver",
    price:"$2100",
    rating:4.2,
    votes:11,
    category:"laptops",
},
{
    id:5,
    name:"iPad Pro 11 inch",
    color:"Space Grey",
    price:"$1099",
    rating:"3.9",
    votes:5,
    category:"tablets",
},
{
    id:6,
    name:"Sennheiser CX 3.00 Wired",
    color:"Black",
    price:"$30",
    rating:4.2,
    votes:1,
    category:"speakers",
},
{
    id:7,
    name:"SONY MDR-XB450AP Wired",
    color:"Black",
    price:"$26",
    rating:4.8,
    votes:5,
    category:"speakers",
},
{
    id:8,
    name:"SAMSUNG Galaxy Tab S6 Lite",
    color:"White",
    price:"$1099",
    rating:"3.6",
    votes:5,
    category:"tablets",
},
{
    id:9,
    name:"Realme Pad 4 GB",
    color:" Grey",
    price:"$1099",
    rating:"3.2",
    votes:5,
    category:"tablets",
},]

export default productsList;


